-- ============================================================
-- seed_regles_dd2024.sql — Module Règles, ruleset DD2024
-- Généré par gen_seed_regles.py — NE PAS éditer à la main.
-- Source : SRD 5.2.1 (Wizards of the Coast LLC) — CC-BY-4.0.
--   https://www.dndbeyond.com/srd
--   https://creativecommons.org/licenses/by/4.0/legalcode
-- Contenu : squelette de chapitres + glossaire complet (renvois .glossaire-lien).
-- Pré-requis : patch_regles.sql exécuté.
-- ============================================================

SET NAMES utf8mb4;

-- Résolution dynamique du ruleset DD2024 (pas d'id entier codé en dur).
SET @ddver := (SELECT var_id FROM dd_variables
               WHERE var_cat = 'ruleset' AND var_valeur = 'DD2024' LIMIT 1);
-- Sécurité : interrompt si le ruleset est introuvable.
SET @ddver := IFNULL(@ddver, (SELECT var_id FROM dd_variables WHERE var_cat='ruleset' AND var_valeur LIKE 'DD2024%' LIMIT 1));

-- Ressource d'attribution SRD 5.2.1 (idempotente).
INSERT INTO dd_ressources (res_nom, res_abreviation, res_selection, res_ruleset_var_id, res_j_id, res_editeur, res_pages, res_description)
SELECT 'System Reference Document 5.2.1', 'SRD 5.2.1', 1, @ddver, NULL, 'Wizards of the Coast LLC', 360,
       'Contenu issu du System Reference Document 5.2.1 (SRD 5.2.1) de Wizards of the Coast LLC, sous licence CC-BY-4.0.'
WHERE @ddver IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM dd_ressources WHERE res_abreviation = 'SRD 5.2.1' AND res_ruleset_var_id = @ddver);
SET @res := (SELECT res_id FROM dd_ressources WHERE res_abreviation = 'SRD 5.2.1' AND res_ruleset_var_id = @ddver LIMIT 1);

SET @now := NOW();

START TRANSACTION;

-- Réinitialisation idempotente des règles DD2024 (FK reg_reg_id : on neutralise d'abord les parents).
SET @fk := @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM dd_regles WHERE reg_ruleset_var_id = @ddver;
SET FOREIGN_KEY_CHECKS = @fk;

INSERT INTO dd_regles
  (reg_id, reg_reg_id, reg_type, reg_nom, reg_slug, reg_texte, reg_ordre,
   reg_ruleset_var_id, reg_res_id, reg_camp_id, reg_visible, reg_date_creation, reg_date_modif)
VALUES
  (1, NULL, 'chapitre', 'Comment jouer', 'comment-jouer', NULL, 0, @ddver, @res, NULL, 1, @now, @now),
  (2, 1, 'chapitre', 'Rythme de jeu', 'rythme-de-jeu', NULL, 0, @ddver, @res, NULL, 1, @now, @now),
  (3, 1, 'chapitre', 'Les six caractéristiques', 'les-six-caracteristiques', NULL, 1, @ddver, @res, NULL, 1, @now, @now),
  (4, 1, 'chapitre', 'Tests d20', 'tests-d20', NULL, 2, @ddver, @res, NULL, 1, @now, @now),
  (5, 1, 'chapitre', 'Maîtrise', 'maitrise', NULL, 3, @ddver, @res, NULL, 1, @now, @now),
  (6, 1, 'chapitre', 'Actions', 'actions', NULL, 4, @ddver, @res, NULL, 1, @now, @now),
  (7, 1, 'chapitre', 'Interactions sociales', 'interactions-sociales', NULL, 5, @ddver, @res, NULL, 1, @now, @now),
  (8, 1, 'chapitre', 'Exploration', 'exploration', NULL, 6, @ddver, @res, NULL, 1, @now, @now),
  (9, 1, 'chapitre', 'Combat', 'combat', NULL, 7, @ddver, @res, NULL, 1, @now, @now),
  (10, 1, 'chapitre', 'Dégâts et soins', 'degats-et-soins', NULL, 8, @ddver, @res, NULL, 1, @now, @now),
  (11, NULL, 'chapitre', 'Création de personnage', 'creation-de-personnage', NULL, 1, @ddver, @res, NULL, 1, @now, @now),
  (12, NULL, 'chapitre', 'Classes', 'classes', NULL, 2, @ddver, @res, NULL, 1, @now, @now),
  (13, NULL, 'chapitre', 'Origines des personnages', 'origines-des-personnages', NULL, 3, @ddver, @res, NULL, 1, @now, @now),
  (14, NULL, 'chapitre', 'Dons', 'dons', NULL, 4, @ddver, @res, NULL, 1, @now, @now),
  (15, NULL, 'chapitre', 'Équipement', 'equipement', NULL, 5, @ddver, @res, NULL, 1, @now, @now),
  (16, NULL, 'chapitre', 'Sorts', 'sorts', NULL, 6, @ddver, @res, NULL, 1, @now, @now),
  (17, NULL, 'chapitre', 'Glossaire de règles', 'glossaire-de-regles', NULL, 7, @ddver, @res, NULL, 1, @now, @now),
  (18, 17, 'glossaire', 'À terre', 'a-terre', '<p>Tant que vous avez l''état À terre, vous subissez les effets suivants.</p><ul><li><strong>Déplacement limité.</strong> Vos seules possibilités de déplacement sont ramper ou vous relever en dépensant la moitié de votre <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> (arrondie à l''inférieur), ce qui met un terme à l''état. Si votre Vitesse est de 0, vous ne pouvez pas vous relever.</li><li><strong>Effet sur les attaques.</strong> Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux jets d''attaque. Un jet d''attaque contre vous reçoit l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a> si l''assaillant se trouve dans un rayon de 1,50 m de vous. Sans cela, ce jet d''attaque subit le Désavantage.</li></ul>', 0, @ddver, @res, NULL, 1, @now, @now),
  (19, 17, 'glossaire', 'Abris', 'abris', '<p>L''abri fournit un degré de protection à la cible située derrière. Il existe trois niveaux d''abri : <strong>Abri partiel</strong> (bonus de +2 à la CA et aux jets de sauvegarde de Dextérité), <strong>Abri supérieur</strong> (bonus de +5 à la CA et aux jets de sauvegarde de Dextérité), et <strong>Abri total</strong> (le sujet ne peut pas être pris pour cible directement). Une cible derrière plusieurs types d''abri ne bénéficie que du degré le plus protecteur.</p>', 1, @ddver, @res, NULL, 1, @now, @now),
  (20, 17, 'glossaire', 'Action', 'action', '<p>À votre tour, vous pouvez entreprendre une action, choisie parmi celles ci-dessous ou parmi les actions spéciales fournies par vos aptitudes.</p><ul><li><a class="glossaire-lien" data-glossaire-slug="attaque">Attaque</a></li><li><a class="glossaire-lien" data-glossaire-slug="desengagement">Désengagement</a></li><li><a class="glossaire-lien" data-glossaire-slug="esquive">Esquive</a></li><li><a class="glossaire-lien" data-glossaire-slug="etude">Étude</a></li><li><a class="glossaire-lien" data-glossaire-slug="furtivite">Furtivité</a></li><li><a class="glossaire-lien" data-glossaire-slug="influence">Influence</a></li><li><a class="glossaire-lien" data-glossaire-slug="intention">Intention</a></li><li><a class="glossaire-lien" data-glossaire-slug="magie">Magie</a></li><li><a class="glossaire-lien" data-glossaire-slug="observation">Observation</a></li><li><a class="glossaire-lien" data-glossaire-slug="pointe">Pointe</a></li><li><a class="glossaire-lien" data-glossaire-slug="soutien">Soutien</a></li><li><a class="glossaire-lien" data-glossaire-slug="utilisation">Utilisation</a></li></ul>', 2, @ddver, @res, NULL, 1, @now, @now),
  (21, 17, 'glossaire', 'Action Bonus', 'action-bonus', '<p>Une action Bonus est une action spéciale que vous pouvez entreprendre au même tour qu''une action. Vous ne pouvez pas entreprendre plus d''une action Bonus par tour, et n''en jouissez que si une règle le stipule explicitement.</p>', 3, @ddver, @res, NULL, 1, @now, @now),
  (22, 17, 'glossaire', 'Agrippé', 'agrippe', '<p>Tant que vous avez l''état Agrippé, vous subissez les effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> 0.</strong> Votre Vitesse est de 0 et ne peut pas augmenter.</li><li><strong>Effet sur les attaques.</strong> Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux jets d''attaque contre toute cible hormis l''agrippeur.</li><li><strong>Déplaçable.</strong> L''agrippeur peut vous tirer ou vous porter lorsqu''il se déplace, mais ses coûts de déplacement sont doublés, sauf si vous êtes de taille TP ou que votre catégorie de taille est inférieure d''au moins deux crans à la sienne.</li></ul>', 4, @ddver, @res, NULL, 1, @now, @now),
  (23, 17, 'glossaire', 'Alignement', 'alignement', '<p>L''alignement d''une créature illustre globalement ses valeurs éthiques et ses idéaux. Il combine la moralité (bon, mauvais ou neutre) et le point de vue vis-à-vis de l''ordre (loyal, chaotique ou neutre), soit neuf combinaisons (Loyal Bon, Neutre Mauvais, etc.).</p>', 5, @ddver, @res, NULL, 1, @now, @now),
  (24, 17, 'glossaire', 'Allié', 'allie', '<p>Une créature est votre alliée si elle appartient à votre groupe d''aventuriers, si elle est votre amie ou figure dans votre camp lors d''un combat, ou si les règles ou le MJ la désignent comme votre alliée.</p>', 6, @ddver, @res, NULL, 1, @now, @now),
  (25, 17, 'glossaire', 'Allonge', 'allonge', '<p>Sauf indication contraire, une créature dispose d''une allonge de 1,50 m.</p>', 7, @ddver, @res, NULL, 1, @now, @now),
  (26, 17, 'glossaire', 'Amical', 'amical', '<p>Une créature Amicale vous considère sous un jour favorable. Vous avez l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a> aux tests de caractéristique visant à influencer une créature Amicale.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="influence">Influence</a>.</p>', 8, @ddver, @res, NULL, 1, @now, @now),
  (27, 17, 'glossaire', 'Arme', 'arme', '<p>Une arme est un objet appartenant à la catégorie des armes courantes ou de guerre.</p>', 9, @ddver, @res, NULL, 1, @now, @now),
  (28, 17, 'glossaire', 'Armes improvisées', 'armes-improvisees', '<p>Une arme improvisée est un objet utilisé pour dépanner comme arme (bouteille cassée, pied de table, poêle à frire…). Une arme courante ou de guerre devient improvisée si l''on s''en sert hors de sa conception initiale.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="maitrise-2">Maîtrise</a>.</strong> N''ajoutez pas votre bonus de maîtrise aux jets d''attaque avec une arme improvisée.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="degats">Dégâts</a>.</strong> Si l''attaque touche, l''arme inflige 1d4 dégâts d''un type que le MJ juge adapté.</li><li><strong>Portée.</strong> Si vous lancez l''arme, sa portée normale est de 6 m et sa portée longue de 18 m.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="arme">Arme</a> équivalente.</strong> Si une arme improvisée est comparable à une arme courante ou de guerre, le MJ peut la traiter comme telle.</li></ul>', 10, @ddver, @res, NULL, 1, @now, @now),
  (29, 17, 'glossaire', 'Arrondis à l''inférieur', 'arrondis-a-l-inferieur', '<p>Chaque fois que vous divisez ou multipliez un nombre et obtenez une fraction, arrondissez à l''entier inférieur même si la fraction est d''un demi ou plus. Certaines règles font exception en indiquant d''arrondir à l''entier supérieur.</p>', 11, @ddver, @res, NULL, 1, @now, @now),
  (30, 17, 'glossaire', 'Asphyxie', 'asphyxie', '<p>Une créature peut retenir son souffle pendant un nombre de minutes égal à 1 + son modificateur de Constitution (minimum 30 secondes). Au-delà, elle reçoit 1 niveau d''<a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a> à la fin de chacun de ses tours. Lorsqu''elle peut à nouveau respirer, elle supprime tous les niveaux d''Épuisement dus à l''asphyxie.</p>', 12, @ddver, @res, NULL, 1, @now, @now),
  (31, 17, 'glossaire', 'Assommer une créature', 'assommer-une-creature', '<p>Lorsque vous êtes censé faire tomber une créature à 0 point de vie avec une attaque de corps à corps, vous pouvez à la place la réduire à 1 point de vie : elle subit l''état <a class="glossaire-lien" data-glossaire-slug="inconscient">Inconscient</a> et entame un <a class="glossaire-lien" data-glossaire-slug="repos-court">Repos court</a>. L''état prend fin si elle récupère des points de vie ou si quelqu''un consacre son action à lui administrer les premiers soins (test de Sagesse [Médecine] DD 10 réussi).</p>', 13, @ddver, @res, NULL, 1, @now, @now),
  (32, 17, 'glossaire', 'Assourdi', 'assourdi', '<p>Tant que vous avez l''état Assourdi, vous subissez l''effet suivant.</p><ul><li><strong>Incapable d''entendre.</strong> Vous n''entendez rien et ratez automatiquement tous les tests de caractéristique reposant sur l''ouïe.</li></ul>', 14, @ddver, @res, NULL, 1, @now, @now),
  (33, 17, 'glossaire', 'Attaque', 'attaque', '<p>Lorsque vous entreprenez l''action Attaque, vous effectuez un jet d''attaque avec arme ou une attaque à mains nues.</p><ul><li><strong>S''équiper et se déséquiper.</strong> Vous pouvez vous équiper ou vous déséquiper d''une arme lors de cette action, avant ou après l''attaque.</li><li><strong>Se déplacer entre les attaques.</strong> Si une aptitude (telle qu''Attaque supplémentaire) vous octroie plusieurs attaques, vous pouvez répartir votre déplacement entre elles.</li></ul>', 15, @ddver, @res, NULL, 1, @now, @now),
  (34, 17, 'glossaire', 'Attaque à mains nues', 'attaque-a-mains-nues', '<p>Au lieu d''une arme, vous pouvez frapper avec votre corps. Chaque fois que vous y recourez, choisissez l''un des effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="degats">Dégâts</a>.</strong> <a class="glossaire-lien" data-glossaire-slug="jet-d-attaque">Jet d''attaque</a> au bonus égal à votre modificateur de Force + bonus de maîtrise. Si l''attaque touche : 1 + votre modificateur de Force dégâts contondants.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="lutte">Lutte</a>.</strong> La cible doit réussir un <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Force ou de Dextérité (son choix) sous peine de subir l''état <a class="glossaire-lien" data-glossaire-slug="agrippe">Agrippé</a>. DD = 8 + mod. de Force + bonus de maîtrise.</li><li><strong>Bousculade.</strong> La cible doit réussir un JS de Force ou de Dextérité (son choix), sinon vous la poussez de 1,50 m ou lui infligez l''état <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a>. DD = 8 + mod. de Force + bonus de maîtrise.</li></ul><p class="glossaire-voir"><em>Lire aussi :</em> Lutte.</p>', 16, @ddver, @res, NULL, 1, @now, @now),
  (35, 17, 'glossaire', 'Attaque d''arme', 'attaque-d-arme', '<p>Une attaque d''arme est un jet d''attaque effectué avec une arme.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="arme">Arme</a>.</p>', 17, @ddver, @res, NULL, 1, @now, @now),
  (36, 17, 'glossaire', 'Attaque de sort', 'attaque-de-sort', '<p>Une attaque de sort est un jet d''attaque effectué dans le cadre d''un sort ou d''un autre effet magique.</p>', 18, @ddver, @res, NULL, 1, @now, @now),
  (37, 17, 'glossaire', 'Attaques d''Opportunité', 'attaques-d-opportunite', '<p>Vous pouvez effectuer une attaque d''Opportunité lorsqu''une créature que vous voyez quitte votre zone d''allonge en recourant à son action, une action Bonus, sa <a class="glossaire-lien" data-glossaire-slug="reaction">Réaction</a> ou l''une de ses vitesses. Vous jouez votre Réaction pour effectuer une attaque de corps à corps avec arme ou à mains nues, juste avant que la créature sorte de votre allonge.</p>', 19, @ddver, @res, NULL, 1, @now, @now),
  (38, 17, 'glossaire', 'Attitude', 'attitude', '<p>Un monstre présente une attitude initiale envers un personnage-joueur : <a class="glossaire-lien" data-glossaire-slug="amical">Amical</a>, <a class="glossaire-lien" data-glossaire-slug="hostile">Hostile</a> ou <a class="glossaire-lien" data-glossaire-slug="indifferent">Indifférent</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> Amical, Hostile, Indifférent, <a class="glossaire-lien" data-glossaire-slug="influence">Influence</a>.</p>', 20, @ddver, @res, NULL, 1, @now, @now),
  (39, 17, 'glossaire', 'Avantage', 'avantage', '<p>Si vous avez l''Avantage à un <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a>, lancez deux d20 et ne retenez que le résultat le plus élevé. Un jet ne peut pas être affecté par plus d''un Avantage, et l''Avantage et le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> sur un même jet s''annulent.</p>', 21, @ddver, @res, NULL, 1, @now, @now),
  (40, 17, 'glossaire', 'Aventure', 'aventure', '<p>Une aventure est une succession de rencontres. Une histoire prend corps au fil des rencontres et aventures successives.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="rencontre">Rencontre</a>.</p>', 22, @ddver, @res, NULL, 1, @now, @now),
  (41, 17, 'glossaire', 'Aveuglé', 'aveugle', '<p>Tant que vous avez l''état Aveuglé, vous subissez les effets suivants.</p><ul><li><strong>Incapable de voir.</strong> Vous ne voyez rien et ratez automatiquement tout test de caractéristique reposant sur la vue.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>, et vos jets d''attaque subissent le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a>.</li></ul>', 23, @ddver, @res, NULL, 1, @now, @now),
  (42, 17, 'glossaire', 'Bris des objets', 'bris-des-objets', '<p>Les objets peuvent être endommagés par les attaques et certains sorts. Un objet extrêmement fragile peut être brisé automatiquement par l''action <a class="glossaire-lien" data-glossaire-slug="attaque">Attaque</a> ou <a class="glossaire-lien" data-glossaire-slug="utilisation">Utilisation</a>.</p><p><strong><a class="glossaire-lien" data-glossaire-slug="classe-d-armure">Classe d''armure</a> des objets.</strong> Tissu/papier/corde 11 ; cristal/verre/glace 13 ; bois 15 ; pierre 17 ; fer/acier 19 ; mithral 21 ; adamantium 23.</p><p><strong><a class="glossaire-lien" data-glossaire-slug="points-de-vie">Points de vie</a> des objets</strong> (taille G ou moins) — fragile / robuste : TP 2 (1d4) / 5 (2d4) ; P 3 (1d6) / 10 (3d6) ; M 4 (1d8) / 18 (4d8) ; G 5 (1d10) / 27 (5d10). Un objet est détruit à 0 point de vie.</p><p><strong><a class="glossaire-lien" data-glossaire-slug="types-de-degats">Types de dégâts</a>.</strong> Les objets ont l''<a class="glossaire-lien" data-glossaire-slug="immunite">Immunité</a> contre les dégâts psychiques et de poison ; le papier et le tissu ont la <a class="glossaire-lien" data-glossaire-slug="vulnerabilite">Vulnérabilité</a> aux dégâts de feu.</p><p><strong><a class="glossaire-lien" data-glossaire-slug="seuil-de-degats">Seuil de dégâts</a>.</strong> Les objets imposants en disposent souvent.</p><p><strong>Absence de valeurs de caractéristique.</strong> Sans valeurs de caractéristique, un objet ne peut pas faire de test de caractéristique et rate ses jets de sauvegarde.</p><p class="glossaire-voir"><em>Lire aussi :</em> Seuil de dégâts.</p>', 24, @ddver, @res, NULL, 1, @now, @now),
  (43, 17, 'glossaire', 'Campagne', 'campagne', '<p>Une campagne est une série d''aventures.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="aventure">Aventure</a>.</p>', 25, @ddver, @res, NULL, 1, @now, @now),
  (44, 17, 'glossaire', 'Capacité de charge', 'capacite-de-charge', '<p>Votre catégorie de taille et votre valeur de Force déterminent le poids maximal que vous pouvez porter. Au-delà de votre capacité de charge, votre <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> est plafonnée à 1,50 m.</p><p>Charge / max pour pousser-tirer-soulever : TP For×3,75 kg / For×7,5 kg ; P et M For×7,5 kg / For×15 kg ; G For×15 kg / For×30 kg ; TG For×30 kg / For×60 kg ; Gig For×60 kg / For×120 kg.</p>', 26, @ddver, @res, NULL, 1, @now, @now),
  (45, 17, 'glossaire', 'Catégorie de taille', 'categorie-de-taille', '<p>Une créature ou un objet appartient à une catégorie de taille : très petite (TP), petite (P), moyenne (M), grande (G), très grande (TG) ou gigantesque (Gig). La taille d''une créature détermine l''espace qu''elle occupe en combat ; celle d''un objet détermine ses points de vie.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="bris-des-objets">Bris des objets</a>.</p>', 27, @ddver, @res, NULL, 1, @now, @now),
  (46, 17, 'glossaire', 'Charmé', 'charme', '<p>Tant que vous avez l''état Charmé, vous subissez les effets suivants.</p><ul><li><strong>Ne pas nuire au charmeur.</strong> Vous ne pouvez pas attaquer votre charmeur ni le cibler avec des aptitudes ou effets magiques qui infligent des dégâts.</li><li><strong>Interaction avec <a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>.</strong> Le charmeur a l''Avantage aux tests de caractéristique d''interaction sociale avec vous.</li></ul>', 28, @ddver, @res, NULL, 1, @now, @now),
  (47, 17, 'glossaire', 'Chute', 'chute', '<p>Au terme d''une chute, une créature subit 1d6 dégâts contondants par tranche de 3 m, jusqu''à un maximum de 20d6, puis subit l''état <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a> (sauf si aucun dégât). Une créature qui tombe dans un liquide peut jouer sa <a class="glossaire-lien" data-glossaire-slug="reaction">Réaction</a> pour un test de Force (Athlétisme) ou de Dextérité (Acrobaties) DD 15 afin d''y entrer par les pieds ou la tête : en cas de réussite, les dégâts de chute sont réduits de moitié.</p>', 29, @ddver, @res, NULL, 1, @now, @now),
  (48, 17, 'glossaire', 'Cible', 'cible', '<p>Une cible est une créature ou un objet visé par un jet d''attaque, soumis à un jet de sauvegarde, ou désigné pour recevoir les effets d''un sort ou d''un autre phénomène.</p>', 30, @ddver, @res, NULL, 1, @now, @now),
  (49, 17, 'glossaire', 'Classe d''armure', 'classe-d-armure', '<p>La classe d''armure (CA) est le nombre à atteindre dans le cadre d''un jet d''attaque. Votre CA de base est égale à 10 + votre modificateur de Dextérité. Si une règle vous octroie un autre mode de calcul, vous en choisissez un seul ; vous ne pouvez pas en cumuler.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="jet-d-attaque">Jet d''attaque</a>.</p>', 31, @ddver, @res, NULL, 1, @now, @now),
  (50, 17, 'glossaire', 'Compétence', 'competence', '<p>Une compétence est un domaine de spécialisation associé à un test de caractéristique. Si vous avez la maîtrise d''une compétence, ajoutez votre bonus de maîtrise au test de caractéristique associé.</p>', 32, @ddver, @res, NULL, 1, @now, @now),
  (51, 17, 'glossaire', 'Concentration', 'concentration', '<p>Certains sorts et effets nécessitent la Concentration pour rester actifs. Si son créateur la perd, l''effet prend fin. La Concentration peut être rompue volontairement (pas d''action requise). Les facteurs suivants la brisent :</p><ul><li><strong>Autre effet nécessitant la Concentration.</strong> Vous la perdez dès que vous lancez un autre sort/effet qui la requiert.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="degats">Dégâts</a>.</strong> Réussissez un <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Constitution. DD = 10 ou la moitié des dégâts subis (arrondi à l''inférieur), le plus élevé, jusqu''à un maximum de 30.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a> ou mort.</strong> La Concentration prend fin si vous subissez l''état Neutralisé ou si vous mourez.</li></ul>', 33, @ddver, @res, NULL, 1, @now, @now),
  (52, 17, 'glossaire', 'Cône', 'cone', '<p>Un Cône est une zone d''effet qui s''étend en ligne droite à partir d''un point d''origine, dans la direction choisie. Sa largeur en un point donné égale la distance qui sépare ce point de l''origine. Le point d''origine n''est pas inclus, sauf décision du créateur.</p>', 34, @ddver, @res, NULL, 1, @now, @now),
  (53, 17, 'glossaire', 'Coup critique', 'coup-critique', '<p>Sur un 20 naturel à un jet d''attaque : l''attaque touche quels que soient les modificateurs et la CA. Tous les dés de dégâts de l''attaque sont lancés deux fois et ajoutés, puis on ajoute les modificateurs applicables.</p>', 35, @ddver, @res, NULL, 1, @now, @now),
  (54, 17, 'glossaire', 'Créature', 'creature', '<p>Toutes les entités du jeu, y compris les personnages-joueurs, sont des créatures.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="type-de-creature">Type de créature</a>.</p>', 36, @ddver, @res, NULL, 1, @now, @now),
  (55, 17, 'glossaire', 'Cube', 'cube', '<p>Un Cube est une zone d''effet qui s''étend en ligne droite à partir d''un point d''origine situé sur l''une de ses faces. L''effet spécifie la longueur de chaque arête. Le point d''origine n''est pas inclus, sauf décision du créateur.</p>', 37, @ddver, @res, NULL, 1, @now, @now),
  (56, 17, 'glossaire', 'Cylindre', 'cylindre', '<p>Un Cylindre est une zone d''effet qui s''étend en ligne droite à partir d''un point d''origine situé au centre de sa face supérieure ou inférieure. L''effet spécifie le rayon de la base et la hauteur. Le point d''origine est inclus dans la zone.</p>', 38, @ddver, @res, NULL, 1, @now, @now),
  (57, 17, 'glossaire', 'Danger', 'danger', '<p>Un danger est un péril lié à l''environnement.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="asphyxie">Asphyxie</a>, <a class="glossaire-lien" data-glossaire-slug="chute">Chute</a>, <a class="glossaire-lien" data-glossaire-slug="deshydratation">Déshydratation</a>, <a class="glossaire-lien" data-glossaire-slug="embrasement">Embrasement</a>, <a class="glossaire-lien" data-glossaire-slug="malnutrition">Malnutrition</a>.</p>', 39, @ddver, @res, NULL, 1, @now, @now),
  (58, 17, 'glossaire', 'Dégâts', 'degats', '<p>Les dégâts sont la représentation chiffrée des préjudices qui font perdre des points de vie à une créature ou à un objet.</p>', 40, @ddver, @res, NULL, 1, @now, @now),
  (59, 17, 'glossaire', 'Degré de difficulté', 'degre-de-difficulte', '<p>Dans le cadre des tests de caractéristique et des jets de sauvegarde, le nombre cible est appelé degré de difficulté (DD).</p>', 41, @ddver, @res, NULL, 1, @now, @now),
  (60, 17, 'glossaire', 'Dés de vie', 'des-de-vie', '<p>Les Dés de vie (DV) déterminent le maximum de points de vie d''un personnage. Une créature peut dépenser des DV pour récupérer des points de vie pendant un <a class="glossaire-lien" data-glossaire-slug="repos-court">Repos court</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> Repos court.</p>', 42, @ddver, @res, NULL, 1, @now, @now),
  (61, 17, 'glossaire', 'Désavantage', 'desavantage', '<p>Si vous avez le Désavantage à un <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a>, lancez deux d20 et ne retenez que le résultat le plus faible. Un jet ne peut pas être affecté par plus d''un Désavantage, et l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a> et le Désavantage sur un même jet s''annulent.</p>', 43, @ddver, @res, NULL, 1, @now, @now),
  (62, 17, 'glossaire', 'Désengagement', 'desengagement', '<p>Si vous entreprenez l''action Désengagement, votre déplacement ne provoque pas d''attaque d''Opportunité jusqu''à la fin du tour.</p>', 44, @ddver, @res, NULL, 1, @now, @now),
  (63, 17, 'glossaire', 'Déshydratation', 'deshydratation', '<p>Une créature qui boit moins de la moitié de ses besoins quotidiens en eau reçoit 1 niveau d''<a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a> à la fin de la journée, qui ne peut être dissipé tant qu''elle n''a pas bu son quota.</p><p>Besoins quotidiens : TP 1 l ; P 4 l ; M 4 l ; G 16 l ; TG 64 l ; Gig 256 l.</p><p class="glossaire-voir"><em>Lire aussi :</em> Épuisement.</p>', 45, @ddver, @res, NULL, 1, @now, @now),
  (64, 17, 'glossaire', 'Effet magique', 'effet-magique', '<p>Un effet est magique s''il est créé par un sort, un objet magique ou un phénomène qu''une règle qualifie de magique.</p>', 46, @ddver, @res, NULL, 1, @now, @now),
  (65, 17, 'glossaire', 'Effets simultanés', 'effets-simultanes', '<p>Si plusieurs événements se produisent en même temps lors d''un même tour, la personne dont c''est le tour (joueur ou MJ) décide de l''ordre dans lequel ils se produisent.</p>', 47, @ddver, @res, NULL, 1, @now, @now),
  (66, 17, 'glossaire', 'Effrayé', 'effraye', '<p>Tant que vous avez l''état Effrayé, vous subissez les effets suivants.</p><ul><li><strong>Effet sur les attaques et les tests.</strong> Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux tests de caractéristique et aux jets d''attaque tant que la source de votre effroi est dans votre champ de vision.</li><li><strong>Impossible d''approcher.</strong> Vous ne pouvez pas vous rapprocher volontairement de la source de votre effroi.</li></ul>', 48, @ddver, @res, NULL, 1, @now, @now),
  (67, 17, 'glossaire', 'Émanation', 'emanation', '<p>Une Émanation est une zone d''effet qui s''étend en ligne droite depuis une créature ou un objet, dans toutes les directions. Elle se déplace avec son origine, sauf effet instantané ou immobile. L''origine n''est pas incluse, sauf décision du créateur.</p>', 49, @ddver, @res, NULL, 1, @now, @now),
  (68, 17, 'glossaire', 'Embrasement', 'embrasement', '<p>Une créature ou un objet victime d''embrasement subit 1d4 dégâts de feu au début de chacun de ses tours. Au prix d''une action, on peut éteindre le feu sur soi en se donnant l''état <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a> et en se roulant au sol ; il s''éteint aussi par arrosage suffisant ou immersion.</p>', 50, @ddver, @res, NULL, 1, @now, @now),
  (69, 17, 'glossaire', 'Empoisonné', 'empoisonne', '<p>Tant que vous avez l''état Empoisonné, vous subissez l''effet suivant.</p><ul><li><strong>Effet sur les attaques et les tests.</strong> Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux jets d''attaque et aux tests de caractéristique.</li></ul>', 51, @ddver, @res, NULL, 1, @now, @now),
  (70, 17, 'glossaire', 'En péril', 'en-peril', '<p>Une créature est En péril dès qu''il lui reste la moitié ou moins de ses points de vie.</p>', 52, @ddver, @res, NULL, 1, @now, @now),
  (71, 17, 'glossaire', 'Ennemi', 'ennemi', '<p>Une créature est votre ennemie si elle s''oppose à vous lors d''un combat, œuvre activement à vous nuire, ou est désignée comme telle par les règles ou le MJ.</p>', 53, @ddver, @res, NULL, 1, @now, @now),
  (72, 17, 'glossaire', 'Entravé', 'entrave', '<p>Tant que vous avez l''état Entravé, vous subissez les effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> 0.</strong> Votre Vitesse est de 0 et ne peut pas augmenter.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>, et vos jets d''attaque subissent le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a>.</li><li><strong>Effet sur les jets de sauvegarde.</strong> Vous subissez le Désavantage aux jets de sauvegarde de Dextérité.</li></ul>', 54, @ddver, @res, NULL, 1, @now, @now),
  (73, 17, 'glossaire', 'Épuisement', 'epuisement', '<p>Tant que vous avez l''état Épuisement, vous subissez les effets suivants.</p><ul><li><strong>Niveaux d''Épuisement.</strong> Cumulatif : chaque occurrence ajoute 1 niveau. Vous mourez au niveau 6.</li><li><strong>Tests d20 affectés.</strong> Vos <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> sont réduits de 2 × votre niveau actuel d''Épuisement.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> réduite.</strong> Votre Vitesse est réduite de 1,50 m × votre niveau actuel.</li><li><strong>Suppression.</strong> Terminer un <a class="glossaire-lien" data-glossaire-slug="repos-long">Repos long</a> dissipe 1 niveau. À 0, l''état prend fin.</li></ul>', 55, @ddver, @res, NULL, 1, @now, @now),
  (74, 17, 'glossaire', 'Escalade', 'escalade', '<p>Lorsque vous escaladez, toute distance parcourue coûte le double de déplacement (le triple en <a class="glossaire-lien" data-glossaire-slug="terrain-difficile">Terrain difficile</a>), sauf si vous disposez d''une <a class="glossaire-lien" data-glossaire-slug="vitesse-d-escalade">Vitesse d''escalade</a>. Une surface glissante peut nécessiter un test de Force (Athlétisme) DD 15.</p>', 56, @ddver, @res, NULL, 1, @now, @now),
  (75, 17, 'glossaire', 'Espace inoccupé', 'espace-inoccupe', '<p>Un espace est inoccupé si aucune créature ne s''y trouve et s''il n''est pas complètement rempli par des objets.</p>', 57, @ddver, @res, NULL, 1, @now, @now),
  (76, 17, 'glossaire', 'Espace occupé', 'espace-occupe', '<p>Un espace est occupé si une créature s''y trouve ou s''il est entièrement rempli par des objets.</p>', 58, @ddver, @res, NULL, 1, @now, @now),
  (77, 17, 'glossaire', 'Esquive', 'esquive', '<p>Si vous entreprenez l''action Esquive : jusqu''au début de votre tour suivant, tout jet d''attaque effectué contre vous par un assaillant que vous voyez subit le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a>, et vos jets de sauvegarde de Dextérité ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>. Vous perdez ces bénéfices si vous subissez l''état <a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a> ou si votre <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> tombe à 0.</p>', 59, @ddver, @res, NULL, 1, @now, @now),
  (78, 17, 'glossaire', 'État', 'etat', '<p>Un état est une situation de jeu temporaire qui vous affecte. Les états définis dans ce glossaire sont :</p><ul><li><a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a></li><li><a class="glossaire-lien" data-glossaire-slug="agrippe">Agrippé</a></li><li><a class="glossaire-lien" data-glossaire-slug="assourdi">Assourdi</a></li><li><a class="glossaire-lien" data-glossaire-slug="aveugle">Aveuglé</a></li><li><a class="glossaire-lien" data-glossaire-slug="charme">Charmé</a></li><li><a class="glossaire-lien" data-glossaire-slug="effraye">Effrayé</a></li><li><a class="glossaire-lien" data-glossaire-slug="empoisonne">Empoisonné</a></li><li><a class="glossaire-lien" data-glossaire-slug="entrave">Entravé</a></li><li><a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a></li><li><a class="glossaire-lien" data-glossaire-slug="etourdi">Étourdi</a></li><li><a class="glossaire-lien" data-glossaire-slug="inconscient">Inconscient</a></li><li><a class="glossaire-lien" data-glossaire-slug="invisible">Invisible</a></li><li><a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a></li><li><a class="glossaire-lien" data-glossaire-slug="paralyse">Paralysé</a></li><li><a class="glossaire-lien" data-glossaire-slug="petrifie">Pétrifié</a></li></ul><p>Un état n''est pas cumulable avec lui-même ; seul l''Épuisement fait exception.</p>', 60, @ddver, @res, NULL, 1, @now, @now),
  (79, 17, 'glossaire', 'Étourdi', 'etourdi', '<p>Tant que vous avez l''état Étourdi, vous subissez les effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a>.</strong> Vous subissez l''état Neutralisé.</li><li><strong>Effet sur les jets de sauvegarde.</strong> Vous ratez automatiquement vos <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Force et de Dextérité.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>.</li></ul>', 61, @ddver, @res, NULL, 1, @now, @now),
  (80, 17, 'glossaire', 'Étude', 'etude', '<p>Lorsque vous entreprenez l''action Étude, vous effectuez un test d''Intelligence en consultant votre mémoire, un livre, un indice ou une autre source de savoir.</p><p>Domaines de savoir : Arcanes (sorts, objets magiques, plans…), Histoire (événements, civilisations…), Investigation (pièges, énigmes…), Nature (terrain, flore, climat…), Religion (divinités, rites…).</p>', 62, @ddver, @res, NULL, 1, @now, @now),
  (81, 17, 'glossaire', 'Expertise', 'expertise', '<p>L''Expertise double votre bonus de maîtrise pour un test de caractéristique effectué avec une maîtrise de compétence concernée (sauf s''il est déjà doublé). Elle s''applique à une compétence dont vous avez la maîtrise et ne peut être obtenue qu''une fois par compétence.</p>', 63, @ddver, @res, NULL, 1, @now, @now),
  (82, 17, 'glossaire', 'Facteur de puissance', 'facteur-de-puissance', '<p>Le Facteur de puissance (FP) synthétise la menace que représente un monstre face à un groupe de quatre personnages. Comparez le FP au niveau des personnages pour estimer le danger.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="profil">Profil</a>.</p>', 64, @ddver, @res, NULL, 1, @now, @now),
  (83, 17, 'glossaire', 'Fiche de personnage', 'fiche-de-personnage', '<p>La fiche de personnage est le document papier ou numérique sur lequel vous consignez les informations relatives à votre personnage.</p>', 65, @ddver, @res, NULL, 1, @now, @now),
  (84, 17, 'glossaire', 'Focaliseur d''incantation', 'focaliseur-d-incantation', '<p>Un focaliseur d''incantation est un objet utilisable à la place des composantes matérielles d''un sort, à condition qu''elles ne soient pas détruites par le sort et n''aient pas de coût spécifié.</p>', 66, @ddver, @res, NULL, 1, @now, @now),
  (85, 17, 'glossaire', 'Formation aux armures', 'formation-aux-armures', '<p>La formation aux armures permet d''utiliser une catégorie d''armures sans inconvénient. Sans formation : <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> à tous les <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> impliquant la Force ou la Dextérité et impossibilité de lancer des sorts ; un bouclier non maîtrisé n''octroie pas son bonus de CA.</p>', 67, @ddver, @res, NULL, 1, @now, @now),
  (86, 17, 'glossaire', 'Furtivité', 'furtivite', '<p>L''action Furtivité permet d''essayer de vous cacher : test de Dextérité (Discrétion) DD 15, à condition d''être en <a class="glossaire-lien" data-glossaire-slug="visibilite-nulle">Visibilité nulle</a>, ou derrière un Abri supérieur ou total, et hors du champ de vision d''un ennemi. En cas de réussite, vous recevez l''état <a class="glossaire-lien" data-glossaire-slug="invisible">Invisible</a> tant que vous restez furtif ; le résultat du test devient le DD à battre pour vous localiser (Sagesse [Perception]). L''état prend fin si vous faites plus de bruit qu''un murmure, êtes détecté, attaquez ou lancez un sort à composante verbale.</p>', 68, @ddver, @res, NULL, 1, @now, @now),
  (87, 17, 'glossaire', 'Harmonisation', 'harmonisation', '<p>Certains objets magiques nécessitent une Harmonisation (lien avec la créature) avant de livrer leurs propriétés. Une créature ne peut pas s''harmoniser avec plus de trois objets magiques à la fois.</p>', 69, @ddver, @res, NULL, 1, @now, @now),
  (88, 17, 'glossaire', 'Hostile', 'hostile', '<p>Une créature Hostile vous considère sous un jour défavorable. Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux tests de caractéristique visant à influencer une créature Hostile.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="influence">Influence</a>.</p>', 70, @ddver, @res, NULL, 1, @now, @now),
  (89, 17, 'glossaire', 'Illusions', 'illusions', '<p>Les sorts et certains effets créent des illusions magiques. L''effet définit ce que fait l''illusion et quels sens elle abuse. Une illusion paraît affectée par l''environnement comme si elle était réelle, sauf indication contraire.</p>', 71, @ddver, @res, NULL, 1, @now, @now),
  (90, 17, 'glossaire', 'Immunité', 'immunite', '<p>Si vous disposez de l''Immunité contre un type de dégâts ou un état, celui-ci ne vous affecte en aucune manière.</p>', 72, @ddver, @res, NULL, 1, @now, @now),
  (91, 17, 'glossaire', 'Inconscient', 'inconscient', '<p>Tant que vous avez l''état Inconscient, vous subissez les effets suivants.</p><ul><li><strong>Inerte.</strong> Vous subissez les états <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a> et <a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a> et laissez choir ce que vous teniez. À la fin de l''état, vous êtes toujours À terre.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> 0.</strong> Votre Vitesse est de 0 et ne peut pas augmenter.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>.</li><li><strong>Effet sur les jets de sauvegarde.</strong> Vous ratez automatiquement vos <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Force et de Dextérité.</li><li><strong>Coups critiques automatiques.</strong> Tout jet d''attaque qui vous touche depuis un rayon de 1,50 m est un <a class="glossaire-lien" data-glossaire-slug="coup-critique">Coup critique</a>.</li><li><strong>Dénué de conscience.</strong> Vous n''avez pas conscience de ce qui vous entoure.</li></ul>', 73, @ddver, @res, NULL, 1, @now, @now),
  (92, 17, 'glossaire', 'Indifférent', 'indifferent', '<p>Une créature Indifférente ne souhaite ni vous aider ni vous gêner. Indifférent est l''attitude par défaut des monstres.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="influence">Influence</a>.</p>', 74, @ddver, @res, NULL, 1, @now, @now),
  (93, 17, 'glossaire', 'Influence', 'influence', '<p>Par l''action Influence, vous incitez un monstre à faire quelque chose. Le MJ détermine s''il se sent disposé, réticent ou hésitant.</p><ul><li><strong>Disposé.</strong> Aucun test : le monstre accède à votre demande.</li><li><strong>Réticent.</strong> Aucun test : le monstre refuse.</li><li><strong>Hésitant.</strong> Un test de caractéristique est nécessaire, affecté par l''attitude du monstre. DD par défaut = 15 ou la valeur d''Intelligence du monstre, le plus élevé.</li></ul><p>Tests d''Influence : Charisme (Intimidation) intimider ; Charisme (Persuasion) convaincre ; Charisme (Représentation) amuser ; Charisme (Tromperie) tromper ; Sagesse (Dressage) amadouer une Bête ou une Monstruosité.</p>', 75, @ddver, @res, NULL, 1, @now, @now),
  (94, 17, 'glossaire', 'Initiative', 'initiative', '<p>L''Initiative détermine la séquence des tours en combat. Le MJ peut demander d''utiliser une valeur d''Initiative = 10 + modificateur de Dextérité (±5 selon <a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>/<a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> au jet).</p>', 76, @ddver, @res, NULL, 1, @now, @now),
  (95, 17, 'glossaire', 'Inspiration héroïque', 'inspiration-heroique', '<p>Si vous, personnage-joueur, disposez de l''Inspiration héroïque, vous pouvez la dépenser pour rejouer aussitôt un dé que vous venez de lancer, en conservant le nouveau jet. Vous ne pouvez pas en cumuler : reçue alors que vous en avez déjà une, elle est perdue, sauf si vous la donnez à un personnage-joueur dépourvu.</p>', 77, @ddver, @res, NULL, 1, @now, @now),
  (96, 17, 'glossaire', 'Intention', 'intention', '<p>L''action Intention consiste à attendre une circonstance avant d''agir : vous définissez un déclencheur perceptible et l''action (ou le déplacement) à jouer en <a class="glossaire-lien" data-glossaire-slug="reaction">Réaction</a>. Pour anticiper un sort, son temps d''incantation doit être d''une action ; retenir ses énergies demande de maintenir la <a class="glossaire-lien" data-glossaire-slug="concentration">Concentration</a> jusqu''au début de votre tour suivant.</p>', 78, @ddver, @res, NULL, 1, @now, @now),
  (97, 17, 'glossaire', 'Invisible', 'invisible', '<p>Tant que vous avez l''état Invisible, vous subissez les effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="surprise">Surprise</a>.</strong> Invisible au moment de jouer l''<a class="glossaire-lien" data-glossaire-slug="initiative">Initiative</a>, vous avez l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a> à ce jet.</li><li><strong>Dissimulé.</strong> Vous n''êtes pas affecté par les effets qui exigent que la cible soit vue, sauf si le créateur vous « voit » par un biais ; votre équipement est aussi dissimulé.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous subissent le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a>, et vos jets d''attaque ont l''Avantage (sauf contre qui vous voit).</li></ul>', 79, @ddver, @res, NULL, 1, @now, @now),
  (98, 17, 'glossaire', 'JS', 'js', '<p>JS est l''acronyme de « jet de sauvegarde ».</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="jet-de-sauvegarde">Jet de sauvegarde</a>.</p>', 80, @ddver, @res, NULL, 1, @now, @now),
  (99, 17, 'glossaire', 'Jet d''attaque', 'jet-d-attaque', '<p>Le jet d''attaque est un <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> qui représente une attaque avec une arme, à mains nues ou avec un sort.</p>', 81, @ddver, @res, NULL, 1, @now, @now),
  (100, 17, 'glossaire', 'Jet de dégâts', 'jet-de-degats', '<p>Un jet de dégâts est un jet de dés, ajusté par tout modificateur applicable, qui inflige des dégâts à une cible.</p>', 82, @ddver, @res, NULL, 1, @now, @now),
  (101, 17, 'glossaire', 'Jet de sauvegarde', 'jet-de-sauvegarde', '<p>Un jet de sauvegarde (<a class="glossaire-lien" data-glossaire-slug="js">JS</a>) représente une tentative d''échapper à une menace ou d''y résister. Vous n''en effectuez que lorsqu''une règle vous y contraint, mais vous pouvez décider d''en rater un sans jet. Sans la valeur de caractéristique associée, vous échouez automatiquement.</p>', 83, @ddver, @res, NULL, 1, @now, @now),
  (102, 17, 'glossaire', 'Jet de sauvegarde contre la mort', 'jet-de-sauvegarde-contre-la-mort', '<p>Un personnage-joueur effectue un jet de sauvegarde contre la mort s''il débute son tour avec 0 point de vie.</p>', 84, @ddver, @res, NULL, 1, @now, @now),
  (103, 17, 'glossaire', 'Ligne', 'ligne', '<p>Une Ligne est une zone d''effet qui s''étend en ligne droite à partir d''un point d''origine et couvre une zone définie par sa longueur et sa largeur. Le point d''origine n''est pas inclus, sauf décision du créateur.</p>', 85, @ddver, @res, NULL, 1, @now, @now),
  (104, 17, 'glossaire', 'Lumière faible', 'lumiere-faible', '<p>Une zone de Lumière faible est à <a class="glossaire-lien" data-glossaire-slug="visibilite-reduite">Visibilité réduite</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> Visibilité réduite.</p>', 86, @ddver, @res, NULL, 1, @now, @now),
  (105, 17, 'glossaire', 'Lumière vive', 'lumiere-vive', '<p>La Lumière vive est synonyme d''éclairage normal.</p>', 87, @ddver, @res, NULL, 1, @now, @now),
  (106, 17, 'glossaire', 'Lutte', 'lutte', '<p>Une créature peut tenter d''en agripper une autre (généralement via une attaque à mains nues).</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="etat">État</a> <a class="glossaire-lien" data-glossaire-slug="agrippe">Agrippé</a>.</strong> Réussir à agripper inflige l''état Agrippé.</li><li><strong>Une lutte par « main ».</strong> L''agrippeur doit avoir une « main » libre (ou partie du corps prévue) et ne peut agripper qu''une créature à la fois avec elle.</li><li><strong>S''extraire.</strong> La cible Agrippée consacre son action à un test de Force (Athlétisme) ou de Dextérité (Acrobaties) contre le DD d''évasion. L''état prend fin aussi si l''agrippeur est <a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a> ou si la distance dépasse son allonge.</li></ul><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="attaque-a-mains-nues">Attaque à mains nues</a>, Agrippé.</p>', 88, @ddver, @res, NULL, 1, @now, @now),
  (107, 17, 'glossaire', 'Magie', 'magie', '<p>Lorsque vous entreprenez l''action Magie, vous lancez un sort dont le temps d''incantation est une action, ou recourez à une aptitude/un objet magique activé par l''action Magie. Un sort d''incantation d''1 minute ou plus requiert l''action Magie à chaque tour et le maintien de la <a class="glossaire-lien" data-glossaire-slug="concentration">Concentration</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> Concentration.</p>', 89, @ddver, @res, NULL, 1, @now, @now),
  (108, 17, 'glossaire', 'Maîtrise', 'maitrise-2', '<p>Si vous avez la maîtrise de quelque chose, vous ajoutez votre bonus de maîtrise à tout <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> effectué en y recourant. Une créature peut maîtriser une compétence, un jet de sauvegarde, une arme ou un outil.</p>', 90, @ddver, @res, NULL, 1, @now, @now),
  (109, 17, 'glossaire', 'Malédictions', 'maledictions', '<p>Certains effets maudissent une créature ou un objet ; l''effet définit le fonctionnement de la malédiction. Elle peut être levée par les sorts délivrance des malédictions et restauration suprême, ou par toute magie qui met explicitement fin aux malédictions.</p>', 91, @ddver, @res, NULL, 1, @now, @now),
  (110, 17, 'glossaire', 'Malnutrition', 'malnutrition', '<p>Une créature qui mange moins de la moitié de ses besoins quotidiens doit réussir un <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Constitution DD 10 sous peine de recevoir 1 niveau d''<a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a> à la fin de la journée. Sans nourriture pendant 5 jours : 1 niveau automatique au 5ᵉ jour, puis 1 niveau par jour suivant.</p><p>Besoins quotidiens : TP 125 g ; P 0,5 kg ; M 0,5 kg ; G 2 kg ; TG 8 kg ; Gig 32 kg.</p><p class="glossaire-voir"><em>Lire aussi :</em> Épuisement.</p>', 92, @ddver, @res, NULL, 1, @now, @now),
  (111, 17, 'glossaire', 'Métamorphes', 'metamorphes', '<p>Si un effet (Forme sauvage, sort métamorphose…) vous permet de changer de forme, sa description précise ce qui vous arrive. Sauf mention contraire, les effets continus (états, sorts, malédictions) se répercutent d''une forme à l''autre. À votre mort, vous reprenez votre forme véritable.</p>', 93, @ddver, @res, NULL, 1, @now, @now),
  (112, 17, 'glossaire', 'Monstre', 'monstre', '<p>Toute créature sous le contrôle du MJ est un monstre, même bien intentionnée.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="creature">Créature</a>, <a class="glossaire-lien" data-glossaire-slug="personnage-non-joueur">Personnage non-joueur</a>.</p>', 94, @ddver, @res, NULL, 1, @now, @now),
  (113, 17, 'glossaire', 'Mort', 'mort', '<p>Une créature morte n''a pas de points de vie et n''en récupère qu''une fois ranimée par une magie telle que rappel à la vie. Sauf mention contraire, elle revient avec les états, contagions et malédictions encore actifs au moment de sa mort, un niveau d''<a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a> de moins, et sans harmonisations.</p>', 95, @ddver, @res, NULL, 1, @now, @now),
  (114, 17, 'glossaire', 'Nage', 'nage', '<p>Lorsque vous nagez, toute distance parcourue coûte le double de déplacement (le triple en <a class="glossaire-lien" data-glossaire-slug="terrain-difficile">Terrain difficile</a>), sauf si vous disposez d''une <a class="glossaire-lien" data-glossaire-slug="vitesse-de-nage">Vitesse de nage</a>. En eau agitée, un test de Force (Athlétisme) DD 15 peut être requis.</p>', 96, @ddver, @res, NULL, 1, @now, @now),
  (115, 17, 'glossaire', 'Neutralisé', 'neutralise', '<p>Tant que vous avez l''état Neutralisé, vous subissez les effets suivants.</p><ul><li><strong>Inactif.</strong> Vous ne pouvez entreprendre ni action, ni action Bonus, ni <a class="glossaire-lien" data-glossaire-slug="reaction">Réaction</a>.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="concentration">Concentration</a> brisée.</strong> Votre Concentration est brisée.</li><li><strong>Sans voix.</strong> Vous ne pouvez pas parler.</li><li><strong>Surpris.</strong> Neutralisé au moment de jouer l''<a class="glossaire-lien" data-glossaire-slug="initiative">Initiative</a>, vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> à ce jet.</li></ul>', 97, @ddver, @res, NULL, 1, @now, @now),
  (116, 17, 'glossaire', 'Objet', 'objet', '<p>Un objet est une chose qui ne vit pas mais que l''on peut désigner. Les bâtiments et assemblages sont faits de plusieurs objets.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="bris-des-objets">Bris des objets</a>.</p>', 98, @ddver, @res, NULL, 1, @now, @now),
  (117, 17, 'glossaire', 'Observation', 'observation', '<p>Lorsque vous entreprenez l''action Observation, vous effectuez un test de Sagesse pour discerner ce qui n''est pas évident.</p><p>Intuition : état d''esprit d''une créature ; Médecine : mal ou cause de mort ; Perception : créature ou objet dissimulé ; Survie : traces ou nourriture.</p>', 99, @ddver, @res, NULL, 1, @now, @now),
  (118, 17, 'glossaire', 'Par jour', 'par-jour', '<p>Si une règle permet de recourir à quelque chose un certain nombre de fois par jour, vous devez terminer un <a class="glossaire-lien" data-glossaire-slug="repos-long">Repos long</a> avant de pouvoir y recourir de nouveau une fois le quota épuisé.</p>', 100, @ddver, @res, NULL, 1, @now, @now),
  (119, 17, 'glossaire', 'Paralysé', 'paralyse', '<p>Tant que vous avez l''état Paralysé, vous subissez les effets suivants.</p><ul><li><strong><a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a>.</strong> Vous subissez l''état Neutralisé.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> 0.</strong> Votre Vitesse est de 0 et ne peut pas augmenter.</li><li><strong>Effet sur les jets de sauvegarde.</strong> Vous ratez automatiquement vos <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Force et de Dextérité.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>.</li><li><strong>Coups critiques automatiques.</strong> Tout jet d''attaque qui vous touche depuis un rayon de 1,50 m est un <a class="glossaire-lien" data-glossaire-slug="coup-critique">Coup critique</a>.</li></ul>', 101, @ddver, @res, NULL, 1, @now, @now),
  (120, 17, 'glossaire', 'Perception des vibrations', 'perception-des-vibrations', '<p>Une créature dotée de la Perception des vibrations localise précisément les créatures et objets en mouvement à une portée définie, à condition d''être en contact avec la même surface ou le même liquide. Elle ne détecte rien dans les airs et n''est pas une forme de vision.</p>', 102, @ddver, @res, NULL, 1, @now, @now),
  (121, 17, 'glossaire', 'Perception passive', 'perception-passive', '<p>La Perception passive reflète la vigilance d''une créature. Elle est égale à 10 + son bonus aux tests de Sagesse (Perception), ±5 selon <a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>/<a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a>.</p>', 103, @ddver, @res, NULL, 1, @now, @now),
  (122, 17, 'glossaire', 'Personnage non-joueur', 'personnage-non-joueur', '<p>Un personnage non-joueur (PNJ) est un monstre qui possède un nom et une personnalité distincte.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="monstre">Monstre</a>.</p>', 104, @ddver, @res, NULL, 1, @now, @now),
  (123, 17, 'glossaire', 'Personnage-joueur', 'personnage-joueur', '<p>Un personnage-joueur (PJ) est un personnage contrôlé par un joueur.</p>', 105, @ddver, @res, NULL, 1, @now, @now),
  (124, 17, 'glossaire', 'Pétrifié', 'petrifie', '<p>Tant que vous avez l''état Pétrifié, vous subissez les effets suivants.</p><ul><li><strong>Transformé en substance inanimée.</strong> Vous (et vos objets non magiques) êtes transformés en une substance dense (souvent la pierre) ; votre poids est décuplé et vous ne vieillissez plus.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a>.</strong> Vous subissez l''état Neutralisé.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> 0.</strong> Votre Vitesse est de 0 et ne peut pas augmenter.</li><li><strong>Effet sur les attaques.</strong> Les jets d''attaque contre vous ont l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a>.</li><li><strong>Effet sur les jets de sauvegarde.</strong> Vous ratez automatiquement vos <a class="glossaire-lien" data-glossaire-slug="js">JS</a> de Force et de Dextérité.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="resistance">Résistance</a> aux dégâts.</strong> Vous avez la Résistance à tous les dégâts.</li><li><strong><a class="glossaire-lien" data-glossaire-slug="immunite">Immunité</a> contre le poison.</strong> Vous avez l''Immunité contre l''état <a class="glossaire-lien" data-glossaire-slug="empoisonne">Empoisonné</a>.</li></ul>', 106, @ddver, @res, NULL, 1, @now, @now),
  (125, 17, 'glossaire', 'Possession', 'possession', '<p>Certains effets font qu''une créature est possédée par une autre. L''effet définit le fonctionnement. La possession est empêchée par protection contre le mal et le bien et dissipée par dissipation du mal et du bien.</p>', 107, @ddver, @res, NULL, 1, @now, @now),
  (126, 17, 'glossaire', 'Pointe', 'pointe', '<p>L''action Pointe vous octroie un déplacement supplémentaire pour ce tour, égal à votre <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> (après modificateurs). Une vitesse spéciale (vol, nage) peut être utilisée à la place.</p><p class="glossaire-voir"><em>Lire aussi :</em> Vitesse.</p>', 108, @ddver, @res, NULL, 1, @now, @now),
  (127, 17, 'glossaire', 'Points d''expérience', 'points-d-experience', '<p>Relever des défis et terminer des aventures rapporte des points d''expérience (PX), attribués par le MJ. Au-delà d''un certain seuil, le niveau du personnage augmente.</p>', 109, @ddver, @res, NULL, 1, @now, @now),
  (128, 17, 'glossaire', 'Points de vie', 'points-de-vie', '<p>Les points de vie (pv) mesurent la difficulté à tuer une créature ou détruire un objet. Les dégâts les réduisent, les soins les rétablissent. Ils ne dépassent pas le maximum et ne descendent pas sous 0.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="bris-des-objets">Bris des objets</a>.</p>', 110, @ddver, @res, NULL, 1, @now, @now),
  (129, 17, 'glossaire', 'Points de vie temporaires', 'points-de-vie-temporaires', '<p>Les points de vie temporaires sont octroyés par certains effets et agissent comme un matelas de sécurité contre la perte de points de vie réels.</p>', 111, @ddver, @res, NULL, 1, @now, @now),
  (130, 17, 'glossaire', 'Profil', 'profil', '<p>Un profil de jeu reprend toutes les données de jeu d''un monstre : catégorie de taille, type de créature, alignement, CA/<a class="glossaire-lien" data-glossaire-slug="initiative">Initiative</a>/pv, <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a>, valeurs de caractéristique, compétences, résistances/vulnérabilités, immunités, sens, langues, FP, traits, actions, etc.</p>', 112, @ddver, @res, NULL, 1, @now, @now),
  (131, 17, 'glossaire', 'Réaction', 'reaction', '<p>Une Réaction est une action spéciale entreprise en réponse à un déclencheur défini. Vous ne pouvez jouer qu''une Réaction entre vos tours. L''attaque d''Opportunité est la Réaction accessible à toutes les créatures.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="attaques-d-opportunite">Attaques d''Opportunité</a>.</p>', 113, @ddver, @res, NULL, 1, @now, @now),
  (132, 17, 'glossaire', 'Rencontre', 'rencontre', '<p>Une rencontre est une scène d''une aventure reposant sur au moins un des trois piliers du jeu : interactions sociales, exploration et combat.</p>', 114, @ddver, @res, NULL, 1, @now, @now),
  (133, 17, 'glossaire', 'Repos court', 'repos-court', '<p>Un Repos court est une période d''inactivité d''au moins 1 heure (se restaurer, discuter, lire, monter la garde). Il faut au moins 1 point de vie pour le commencer.</p><ul><li><strong>Dépense de dés de vie.</strong> Dépensez des DV pour récupérer des points de vie (jet du dé + modificateur de Constitution, minimum 1).</li><li><strong>Aptitudes spéciales.</strong> Certaines aptitudes se rechargent au terme d''un Repos court.</li></ul><p>Interrompu par : jouer l''<a class="glossaire-lien" data-glossaire-slug="initiative">Initiative</a>, lancer un sort autre qu''un sort mineur, subir des dégâts. Un Repos court interrompu n''octroie aucun bénéfice.</p>', 115, @ddver, @res, NULL, 1, @now, @now),
  (134, 17, 'glossaire', 'Repos long', 'repos-long', '<p>Un Repos long est une période d''au moins 8 heures (au moins 6 h de sommeil + 2 h de menues tâches). Le sommeil impose l''état <a class="glossaire-lien" data-glossaire-slug="inconscient">Inconscient</a>. Il faut attendre 16 heures entre deux Repos longs, et avoir au moins 1 point de vie pour le commencer.</p><ul><li><strong>Récupération de tous les pv.</strong> Tous les pv perdus et les DV dépensés sont récupérés ; le maximum de pv réduit revient à la normale.</li><li><strong>Récupération des caractéristiques.</strong> Les valeurs de caractéristique réduites reviennent à la normale.</li><li><strong>Réduction de l''<a class="glossaire-lien" data-glossaire-slug="epuisement">Épuisement</a>.</strong> Le niveau d''Épuisement diminue de 1.</li><li><strong>Aptitudes spéciales.</strong> Certaines aptitudes se rechargent au terme d''un Repos long.</li></ul><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="repos-court">Repos court</a>.</p>', 116, @ddver, @res, NULL, 1, @now, @now),
  (135, 17, 'glossaire', 'Reptation', 'reptation', '<p>Lorsque vous rampez, toute distance parcourue coûte le double de déplacement (le triple en <a class="glossaire-lien" data-glossaire-slug="terrain-difficile">Terrain difficile</a>).</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a>.</p>', 117, @ddver, @res, NULL, 1, @now, @now),
  (136, 17, 'glossaire', 'Résistance', 'resistance', '<p>Si vous bénéficiez de la Résistance à un type de dégâts, ces dégâts sont réduits de moitié contre vous. La Résistance ne s''applique qu''une seule fois à des dégâts donnés.</p>', 118, @ddver, @res, NULL, 1, @now, @now),
  (137, 17, 'glossaire', 'Rituel', 'rituel', '<p>Un sort préparé portant la mention « rituel » peut être lancé sous forme de rituel : 10 minutes de plus que l''incantation normale, mais sans dépenser d''emplacement (et donc sans pouvoir être monté en niveau).</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="sort">Sort</a>.</p>', 119, @ddver, @res, NULL, 1, @now, @now),
  (138, 17, 'glossaire', 'Saut', 'saut', '<p>Lorsque vous sautez, vous effectuez soit un saut en longueur (horizontal), soit un saut en hauteur (vertical).</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="saut-en-longueur">Saut en longueur</a>, <a class="glossaire-lien" data-glossaire-slug="saut-en-hauteur">Saut en hauteur</a>.</p>', 120, @ddver, @res, NULL, 1, @now, @now),
  (139, 17, 'glossaire', 'Saut en hauteur', 'saut-en-hauteur', '<p>Vous bondissez d''une distance maximale égale à 90 cm + (modificateur de Force × 30 cm) avec une course d''élan d''au moins 3 m (moitié sans élan). La distance est décomptée de votre déplacement.</p>', 121, @ddver, @res, NULL, 1, @now, @now),
  (140, 17, 'glossaire', 'Saut en longueur', 'saut-en-longueur', '<p>Vous bondissez horizontalement d''une distance maximale égale à votre valeur de Force × 30 cm avec une course d''élan d''au moins 3 m (moitié sans élan). Atterrir en <a class="glossaire-lien" data-glossaire-slug="terrain-difficile">Terrain difficile</a> demande un test de Dextérité (Acrobaties) DD 10 sous peine de l''état <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a>.</p>', 122, @ddver, @res, NULL, 1, @now, @now),
  (141, 17, 'glossaire', 'Seuil de dégâts', 'seuil-de-degats', '<p>Une créature ou un objet avec un seuil de dégâts a l''<a class="glossaire-lien" data-glossaire-slug="immunite">Immunité</a> contre tous les dégâts, sauf si une même attaque/effet inflige une somme supérieure au seuil, auquel cas les dégâts s''appliquent pleinement. Les dégâts inférieurs au seuil sont superficiels et ne réduisent pas les points de vie.</p>', 123, @ddver, @res, NULL, 1, @now, @now),
  (142, 17, 'glossaire', 'Soins', 'soins', '<p>Les soins permettent de récupérer des points de vie.</p>', 124, @ddver, @res, NULL, 1, @now, @now),
  (143, 17, 'glossaire', 'Sort', 'sort', '<p>Un sort est un effet magique dont les propriétés sont décrites au chapitre « Sorts ».</p>', 125, @ddver, @res, NULL, 1, @now, @now),
  (144, 17, 'glossaire', 'Sort mineur', 'sort-mineur', '<p>Un sort mineur est un sort de niveau 0, lancé sans dépenser d''emplacement de sort.</p>', 126, @ddver, @res, NULL, 1, @now, @now),
  (145, 17, 'glossaire', 'Soutien', 'soutien', '<p>Lorsque vous entreprenez l''action Soutien, vous faites l''une des deux choses suivantes.</p><ul><li><strong>Assister un test de caractéristique.</strong> Un allié proche a l''<a class="glossaire-lien" data-glossaire-slug="avantage">Avantage</a> à son prochain test avec une compétence ou un outil dont vous avez la maîtrise (jusqu''au début de votre tour suivant).</li><li><strong>Assister un jet d''attaque.</strong> Vous distrayez un ennemi dans un rayon de 1,50 m : un allié a l''Avantage à son prochain jet d''attaque contre cet ennemi.</li></ul>', 127, @ddver, @res, NULL, 1, @now, @now),
  (146, 17, 'glossaire', 'Sphère', 'sphere', '<p>Une Sphère est une zone d''effet qui s''étend en ligne droite dans toutes les directions à partir d''un point d''origine. L''effet stipule le rayon. Le point d''origine est inclus dans la zone.</p>', 128, @ddver, @res, NULL, 1, @now, @now),
  (147, 17, 'glossaire', 'Stabilisé', 'stabilise', '<p>Une créature est Stabilisée si elle a 0 point de vie mais n''a pas à effectuer de jets de sauvegarde contre la mort.</p>', 129, @ddver, @res, NULL, 1, @now, @now),
  (148, 17, 'glossaire', 'Surprise', 'surprise', '<p>Une créature prise au dépourvu au début d''un combat est surprise : elle subit le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> à son jet d''<a class="glossaire-lien" data-glossaire-slug="initiative">Initiative</a>.</p>', 130, @ddver, @res, NULL, 1, @now, @now),
  (149, 17, 'glossaire', 'Télépathie', 'telepathie', '<p>La télépathie est une faculté magique de communication mentale à une portée définie. La créature contactée doit comprendre au moins une langue ou être télépathe. Le contact est rompu si l''un des deux est <a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a>, ou si la cible quitte la portée.</p>', 131, @ddver, @res, NULL, 1, @now, @now),
  (150, 17, 'glossaire', 'Téléportation', 'teleportation', '<p>La téléportation est un transport magique instantané, sans franchir l''espace intermédiaire ; elle ne dépense pas de déplacement (sauf mention) et ne provoque jamais d''attaque d''Opportunité. Votre équipement vous suit ; une destination occupée vous fait réapparaître dans l''espace inoccupé le plus proche.</p>', 132, @ddver, @res, NULL, 1, @now, @now),
  (151, 17, 'glossaire', 'Ténèbres', 'tenebres', '<p>Une zone de Ténèbres est une zone à <a class="glossaire-lien" data-glossaire-slug="visibilite-nulle">Visibilité nulle</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> Visibilité nulle.</p>', 133, @ddver, @res, NULL, 1, @now, @now),
  (152, 17, 'glossaire', 'Terrain difficile', 'terrain-difficile', '<p>Dans un Terrain difficile, le coût de déplacement est doublé (1,50 m coûte 3 m). Il n''est pas cumulatif. Un espace est un Terrain difficile s''il contient, entre autres : une créature qui n''est ni TP ni alliée, du mobilier, neige/glace/éboulis/taillis, un liquide de profondeur intermédiaire, une ouverture étroite, ou une pente de 20° ou plus.</p>', 134, @ddver, @res, NULL, 1, @now, @now),
  (153, 17, 'glossaire', 'Test d20', 'test-d20', '<p>La notion de Test d20 englobe les trois principaux jets de d20 : tests de caractéristique, jets d''attaque et jets de sauvegarde. Tout élément affectant les Tests d20 affecte ces trois jets.</p>', 135, @ddver, @res, NULL, 1, @now, @now),
  (154, 17, 'glossaire', 'Test de caractéristique', 'test-de-caracteristique', '<p>Un test de caractéristique est un <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> représentant le recours à l''une des six caractéristiques (ou à une compétence associée) pour surmonter une épreuve.</p>', 136, @ddver, @res, NULL, 1, @now, @now),
  (155, 17, 'glossaire', 'Type de créature', 'type-de-creature', '<p>Toutes les créatures sont associées à un type. Types du jeu :</p><ul><li>Aberration</li><li>Artificiel</li><li>Bête</li><li>Céleste</li><li>Dragon</li><li>Élémentaire</li><li>Fée</li><li>Fiélon</li><li>Géant</li><li>Humanoïde</li><li>Monstruosité</li><li>Mort-vivant</li><li>Plante</li><li>Vase</li></ul>', 137, @ddver, @res, NULL, 1, @now, @now),
  (156, 17, 'glossaire', 'Types de dégâts', 'types-de-degats', '<p>Les effets infligent différents types de dégâts (sans règle propre, mais d''autres règles comme la <a class="glossaire-lien" data-glossaire-slug="resistance">Résistance</a> les prennent en compte) :</p><ul><li>Acide</li><li>Contondants</li><li>Feu</li><li>Force</li><li>Foudre</li><li>Froid</li><li>Nécrotiques</li><li>Perforants</li><li>Poison</li><li>Psychiques</li><li>Radiants</li><li>Tonnerre</li><li>Tranchants</li></ul>', 138, @ddver, @res, NULL, 1, @now, @now),
  (157, 17, 'glossaire', 'Utilisation', 'utilisation', '<p>Vous interagissez souvent avec un objet en faisant autre chose (dégainer dans le cadre de l''action <a class="glossaire-lien" data-glossaire-slug="attaque">Attaque</a>). Lorsqu''un objet requiert spécifiquement votre action, vous entreprenez l''action Utilisation.</p>', 139, @ddver, @res, NULL, 1, @now, @now),
  (158, 17, 'glossaire', 'Valeur et modificateur de caractéristique', 'valeur-et-modificateur-de-caracteristique', '<p>Toute créature dispose de six valeurs de caractéristique (Force, Dextérité, Constitution, Intelligence, Sagesse, Charisme), chacune dotée d''un modificateur ajouté aux <a class="glossaire-lien" data-glossaire-slug="test-d20">Test d20</a> correspondants.</p>', 140, @ddver, @res, NULL, 1, @now, @now),
  (159, 17, 'glossaire', 'Visibilité nulle', 'visibilite-nulle', '<p>Vous subissez l''état <a class="glossaire-lien" data-glossaire-slug="aveugle">Aveuglé</a> lorsque vous essayez de voir dans un espace à Visibilité nulle.</p><p class="glossaire-voir"><em>Lire aussi :</em> Aveuglé, <a class="glossaire-lien" data-glossaire-slug="tenebres">Ténèbres</a>.</p>', 141, @ddver, @res, NULL, 1, @now, @now),
  (160, 17, 'glossaire', 'Visibilité réduite', 'visibilite-reduite', '<p>Vous subissez le <a class="glossaire-lien" data-glossaire-slug="desavantage">Désavantage</a> aux tests de Sagesse (Perception) visant à voir dans un espace à Visibilité réduite.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="lumiere-faible">Lumière faible</a>.</p>', 142, @ddver, @res, NULL, 1, @now, @now),
  (161, 17, 'glossaire', 'Vision aveugle', 'vision-aveugle', '<p>Avec la Vision aveugle, vous « voyez » à la portée indiquée sans recourir à la vue : vous percevez tout ce qui ne bénéficie pas d''un Abri total, même <a class="glossaire-lien" data-glossaire-slug="aveugle">Aveuglé</a> ou dans les <a class="glossaire-lien" data-glossaire-slug="tenebres">Ténèbres</a>, y compris ce qui a l''état <a class="glossaire-lien" data-glossaire-slug="invisible">Invisible</a>.</p>', 143, @ddver, @res, NULL, 1, @now, @now),
  (162, 17, 'glossaire', 'Vision dans le noir', 'vision-dans-le-noir', '<p>Avec la Vision dans le noir, vous voyez en <a class="glossaire-lien" data-glossaire-slug="lumiere-faible">Lumière faible</a> comme en <a class="glossaire-lien" data-glossaire-slug="lumiere-vive">Lumière vive</a> à la portée indiquée, et dans les <a class="glossaire-lien" data-glossaire-slug="tenebres">Ténèbres</a> comme en Lumière faible (couleurs en nuances de gris).</p>', 144, @ddver, @res, NULL, 1, @now, @now),
  (163, 17, 'glossaire', 'Vision lucide', 'vision-lucide', '<p>Avec la Vision lucide, à la portée indiquée, votre vision s''affranchit des <a class="glossaire-lien" data-glossaire-slug="tenebres">Ténèbres</a> (normales comme magiques), de l''Invisibilité, des illusions visuelles (transparentes, <a class="glossaire-lien" data-glossaire-slug="js">JS</a> réussis automatiquement) et des métamorphoses (forme véritable visible) ; vous voyez aussi dans le Plan Éthéré.</p>', 145, @ddver, @res, NULL, 1, @now, @now),
  (164, 17, 'glossaire', 'Vitesse', 'vitesse', '<p>Chaque créature dispose d''une Vitesse : la distance en mètres qu''elle peut parcourir en se déplaçant pendant son tour. Certaines créatures ont des vitesses spéciales (escalade, fouissement, nage, vol) ; si un effet modifie la Vitesse, les vitesses spéciales sont modifiées du même montant.</p>', 146, @ddver, @res, NULL, 1, @now, @now),
  (165, 17, 'glossaire', 'Vitesse d''escalade', 'vitesse-d-escalade', '<p>Une <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> d''escalade remplace la Vitesse pour gravir une surface verticale sans le surcoût de déplacement habituel de l''escalade.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="escalade">Escalade</a>, Vitesse.</p>', 147, @ddver, @res, NULL, 1, @now, @now),
  (166, 17, 'glossaire', 'Vitesse de fouissement', 'vitesse-de-fouissement', '<p>Une <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> de fouissement permet de se mouvoir dans le sable, la terre, la boue ou la glace (pas dans le roc, sauf trait spécial).</p><p class="glossaire-voir"><em>Lire aussi :</em> Vitesse.</p>', 148, @ddver, @res, NULL, 1, @now, @now),
  (167, 17, 'glossaire', 'Vitesse de nage', 'vitesse-de-nage', '<p>Une <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> de nage permet de nager sans le surcoût de déplacement habituel de la nage.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="nage">Nage</a>, Vitesse.</p>', 149, @ddver, @res, NULL, 1, @now, @now),
  (168, 17, 'glossaire', 'Vitesse de vol', 'vitesse-de-vol', '<p>Une <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> de vol permet de se déplacer dans les airs. Tant que vous en disposez, vous restez en l''air jusqu''à vous poser, tomber ou mourir.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="vol">Vol</a>, Vitesse.</p>', 150, @ddver, @res, NULL, 1, @now, @now),
  (169, 17, 'glossaire', 'Vol', 'vol', '<p>Divers effets permettent de voler. En volant, vous tombez si vous subissez l''état <a class="glossaire-lien" data-glossaire-slug="neutralise">Neutralisé</a> ou <a class="glossaire-lien" data-glossaire-slug="a-terre">À terre</a>, ou si votre <a class="glossaire-lien" data-glossaire-slug="vitesse-de-vol">Vitesse de vol</a> tombe à 0 — sauf si vous disposez du <a class="glossaire-lien" data-glossaire-slug="vol-stationnaire">Vol stationnaire</a>.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="chute">Chute</a>, <a class="glossaire-lien" data-glossaire-slug="vitesse">Vitesse</a> de vol.</p>', 151, @ddver, @res, NULL, 1, @now, @now),
  (170, 17, 'glossaire', 'Vol stationnaire', 'vol-stationnaire', '<p>Certaines créatures peuvent rester en vol stationnaire (indiqué dans leur profil ou octroyé par un effet), ce qui empêche de tomber dans certaines circonstances.</p><p class="glossaire-voir"><em>Lire aussi :</em> <a class="glossaire-lien" data-glossaire-slug="vol">Vol</a>.</p>', 152, @ddver, @res, NULL, 1, @now, @now),
  (171, 17, 'glossaire', 'Vulnérabilité', 'vulnerabilite', '<p>Si vous présentez une Vulnérabilité à un type de dégâts, ils sont doublés contre vous. La Vulnérabilité ne s''applique qu''une seule fois à des dégâts donnés.</p>', 153, @ddver, @res, NULL, 1, @now, @now),
  (172, 17, 'glossaire', 'Zone d''effet', 'zone-d-effet', '<p>De nombreux sorts et aptitudes ont une zone d''effet, prenant l''une des six formes suivantes :</p><ul><li><a class="glossaire-lien" data-glossaire-slug="cone">Cône</a></li><li><a class="glossaire-lien" data-glossaire-slug="cube">Cube</a></li><li><a class="glossaire-lien" data-glossaire-slug="cylindre">Cylindre</a></li><li><a class="glossaire-lien" data-glossaire-slug="emanation">Émanation</a></li><li><a class="glossaire-lien" data-glossaire-slug="ligne">Ligne</a></li><li><a class="glossaire-lien" data-glossaire-slug="sphere">Sphère</a></li></ul><p>Chaque zone d''effet a un point d''origine ; pour bloquer une ligne vers un point, un obstacle doit offrir un Abri total.</p>', 154, @ddver, @res, NULL, 1, @now, @now),
  (173, NULL, 'chapitre', 'Boîte à outils ludique', 'boite-a-outils-ludique', NULL, 8, @ddver, @res, NULL, 1, @now, @now),
  (174, NULL, 'chapitre', 'Objets magiques', 'objets-magiques', NULL, 9, @ddver, @res, NULL, 1, @now, @now),
  (175, NULL, 'chapitre', 'Monstres', 'monstres', NULL, 10, @ddver, @res, NULL, 1, @now, @now);

COMMIT;

-- Récapitulatif
--   Chapitres (skeleton)  : 20
--   Termes de glossaire   : 155
--   Total nœuds insérés   : 175
